export const dayoutPackage = [
  {
    id: 1,
    name: "Kids Fun Package",
    description: "A delightful package filled with engaging activities and fun surprises. Perfectly designed to keep kids entertained all day long.",
    price: 1500,
    includesBreakfast: true,
    includesDinner: false,
    category: "Kids",
  },
  {
    id: 2,
    name: "Kids All-Inclusive Package",
    description: "An all-inclusive plan featuring full meals and exciting activities for kids. Guaranteed to provide a joyful and memorable experience.",
    price: 1800,
    includesBreakfast: true,
    includesDinner: true,
    category: "Kids",
  },
  {
    id: 3,
    name: "Adult Standard Package",
    description: "Enjoy a comfortable stay with basic yet essential amenities. A perfect choice for budget-conscious travelers seeking relaxation.",
    price: 2100,
    includesBreakfast: false,
    includesDinner: false,
    category: "Adult",
  },
  {
    id: 4,
    name: "Adult Breakfast Package",
    description: "A comfortable stay accompanied by a complimentary breakfast. Ideal for those who want a hassle-free start to their day.",
    price: 2200,
    includesBreakfast: true,
    includesDinner: false,
    category: "Adult",
  },
  {
    id: 5,
    name: "Adult Dinner Package",
    description: "This package includes a relaxing dinner at our fine-dining restaurant. Perfect for unwinding and enjoying an elegant evening.",
    price: 2500,
    includesBreakfast: false,
    includesDinner: true,
    category: "Adult",
  },
  {
    id: 6,
    name: "Adult All-Inclusive Package",
    description: "An all-inclusive package offering all meals and premium facilities. Ideal for a luxurious and hassle-free getaway.",
    price: 2555,
    includesBreakfast: true,
    includesDinner: true,
    category: "Adult",
  },
];
